openapi: 3.0.3
info:
  title: REST API Microservice Demo
  description: A simple REST API microservice.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /messages:
    get:
      summary: Get all messages
      operationId: getMessages
      responses:
        '200':
          description: A list of messages
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
    post:
      summary: Create a new message
      operationId: createMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        '201':
          description: Message created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedMessage'

  /messages/{messageId}:
    get:
      summary: Get a message by ID
      operationId: getMessageById
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: A message with metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DetailedMessage'
        '404':
          description: Message not found
    delete:
      summary: Delete a message by ID
      operationId: deleteMessage
      parameters:
        - name: messageId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Message deleted
        '404':
          description: Message not found

components:
  schemas:
    Message:
      type: object
      properties:
        id:
          type: integer
          format: int64
        payload:
          type: string
      required:
        - id
        - payload

    MessageMetadata:
      type: object
      properties:
        palindrome:
          type: boolean

    DetailedMessage:
      type: object
      properties:
        message:
          $ref: '#/components/schemas/Message'
        metadata:
          $ref: '#/components/schemas/MessageMetadata'
      required:
        - message
        - metadata