openapi: 3.0.0
info:
  title: REST API for Demo
  license:
    name: BSD-3-Clause
    url: https://opensource.org/license/BSD-3-Clause
  version: 1.0.0
servers:
- url: /
paths:
  /messages:
    get:
      tags:
      - messages
      summary: List all messages
      operationId: listMessages
      parameters:
      - name: limit
        in: query
        description: How many messages to return at one time (max 100)
        required: false
        style: form
        explode: true
        schema:
          maximum: 100
          minimum: 0
          type: integer
          format: uint64
          default: 20
      - name: afterId
        in: query
        description: Show messages after a specified ID
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: uint64
          default: 0
      - name: detailed
        in: query
        description: Include metadata
        required: false
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      responses:
        "200":
          description: "Success: Returns a paged array of messages"
          headers:
            x-next-relative-url:
              description: A relative URL for the next page of messages
              style: simple
              explode: false
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: "Failure (Invalid Request): Returns null response"
        "422":
          description: "Failure (Unprocessable): Returns null response"
    post:
      tags:
      - messages
      summary: Create a message
      operationId: createMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      responses:
        "201":
          description: "Success: Returns null response"
        "400":
          description: "Failure (Invalid Request): Returns null response"
        "422":
          description: "Failure (Unprocessable): Returns null response"
  /messages/{messageId}:
    get:
      tags:
      - messages
      summary: Get a specific message by ID
      operationId: getMessageById
      parameters:
      - name: messageId
        in: path
        description: The ID of the message
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: uint64
      - name: detailed
        in: query
        description: Include metadata
        required: false
        style: form
        explode: true
        schema:
          type: boolean
          default: false
      responses:
        "200":
          description: "Success: Returns specified message"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "404":
          description: "Failure (Not found): Returns null response"
    put:
      tags:
      - messages
      summary: Update a specific message by ID
      operationId: updateMessageById
      parameters:
      - name: messageId
        in: path
        description: The ID of the message
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: uint64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      responses:
        "204":
          description: "Success: Returns null response"
        "404":
          description: "Failure (Not found): Returns null response"
        "422":
          description: "Failure (Unprocessable): Returns null response"
    delete:
      tags:
      - messages
      summary: Delete a specific message by ID
      operationId: deleteMessageById
      parameters:
      - name: messageId
        in: path
        description: The ID of the message
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: uint64
      responses:
        "204":
          description: "Success: Returns null response"
        "404":
          description: "Failure (Not found): Returns null response"
        "422":
          description: "Failure (Unprocessable): Returns null response"
components:
  schemas:
    Message:
      required:
      - payload
      type: object
      properties:
        id:
          type: integer
          format: uint64
        payload:
          type: string
    DetailedMessage:
      required:
      - message
      - metadata
      type: object
      properties:
        message:
          $ref: '#/components/schemas/Message'
        metadata:
          $ref: '#/components/schemas/DetailedMessage_metadata'
    Messages:
      maxItems: 100
      type: array
      items:
        $ref: '#/components/schemas/Message'
    DetailedMessages:
      maxItems: 100
      type: array
      items:
        $ref: '#/components/schemas/DetailedMessage'
    inline_response_200:
      oneOf:
      - $ref: '#/components/schemas/Messages'
      - $ref: '#/components/schemas/DetailedMessages'
    inline_response_200_1:
      oneOf:
      - $ref: '#/components/schemas/Message'
      - $ref: '#/components/schemas/DetailedMessage'
    DetailedMessage_metadata:
      required:
      - palindrome
      type: object
      properties:
        palindrome:
          type: boolean
