/*
 * REST API for Demo
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Message struct {
	Id int32 `json:"id,omitempty"`
	Payload string `json:"payload"`
}
