/*
 * REST API for Demo
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DetailedMessage struct {
	Message *Message `json:"message"`
	Metadata *DetailedMessageMetadata `json:"metadata"`
}
